### ISSUE TITLE
Player Camera

### ISSUE THREAD

**Issue by actuallylost** [maikkundev/noora#6]
This issue represents the requirements for the Player's camera to work as intended.

## Tasks
- [x] Add Camera2D node inside main Game scene.
- [x] Make Camera follow player.
- [x] Make Camera have player at the center of the screen.

All implemented with #7
